import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/components/ThemeProvider';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import Provider from '@/components/Provider';
import { Toaster } from 'react-hot-toast';

const recursive = Raleway({
  subsets: ['latin'],
  weight: '400',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={recursive.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Navbar />
            <main className=' flex flex-col min-h-[calc(100vh-3.5rem-1px)]'>
              {children}
            </main>
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
